services:
    openjdk:
        container_name: openjdk
        image: openjdk:latest
        ports:
            - 8080:8080
        volumes:
            - ./target:/target
        command: bash -c "java -jar /target/demo-0.0.1-SNAPSHOT.jar"
